/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.test.NiceClass;

public class App {

    public static void main(String[] args) {
        NiceClass.niceHelperMethod();
    }
}
